# Para começar com as atualizações de versão do Dependabot, você precisará especificar qual
# ecossistemas de pacotes a serem atualizados e onde os manifestos do pacote estão localizados.
# Consulte a documentação para todas as opções de configuração:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-update

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "./app" #Caminho para o diretório onde está o arquivo do gerenciador de pacotes (package.json, composer.json, etc.)
    schedule:
      interval: "monthly" #Intervalo de verificação das atualizações (diário, semanal, mensal)
