name: Automerge Dependabot PRs

on:
  pull_request:
    types:
      - opened

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
    - name: Check if the PR is from Dependabot
      id: check_dependabot
      run: echo "::set-output name=dependabot::${{ contains(github.actor, 'dependabot') }}"

    - name: Merge PR
      if: steps.check_dependabot.outputs.dependabot == 'true'
      run: |
        # Merge the PR using GitHub API or your preferred method
        # Replace with your logic to merge the PR
