name: automerge

on:
  pull_request:
    types:
      - labeled
  pull_request_target:
    types:
      - labeled

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "ahmadnassri/action-dependabot-auto-merge@v2"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
